# Generated by Django 5.2.3 on 2025-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=50)),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('container_status', models.CharField(max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
